name: Tests ui-kit

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.16.0'
      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm test
