name: Release Candidate

on:
  push:
    branches:
      - release/**
      - hotfix/**

jobs:
  build-and-publish:
    name: Build and publish package
    runs-on: ubuntu-latest
    steps:
      - name: Extract version
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#*/v*})"
        id: tag
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
#          cache: 'npm'
      - run: git init&& git config user.name "Unique" && git config user.email "uikit@unique.network"
      - run: npm version ${{ steps.tag.outputs.tag }}-rc
      - name: Set prerelease version
        shell: bash
        run: echo "##[set-output name=version;]$(echo $(npm version prerelease))"
        id: version
#      - run: npm install

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: GitHub
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_MESSAGE: Just published Release Candidate with ver *${{ steps.version.outputs.version#v* }}*
          SLACK_FOOTER: "___"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_UI_KIT_UPDATES }}


